import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        {/* Sidebar */}
        <aside className="w-56 min-h-screen bg-gray-100 border-r flex flex-col">
          <div className="p-6 font-bold text-xl">News App</div>
          <nav className="flex-1 flex flex-col gap-2 px-4">
            <Link href="/" className="flex items-center gap-2 px-3 py-2 rounded hover:bg-gray-200 transition-colors">
              {/* Home icon (SVG) */}
              <span aria-hidden="true">
                <svg width="20" height="20" fill="none" viewBox="0 0 24 24"><path stroke="#222" strokeWidth="2" d="M3 11.5 12 5l9 6.5M5 10.5V19a1 1 0 0 0 1 1h3m8-9.5V19a1 1 0 0 1-1 1h-3m-4 0h4"/></svg>
              </span>
              News
            </Link>
            <Link href="/settings" className="flex items-center gap-2 px-3 py-2 rounded hover:bg-gray-200 transition-colors">
              {/* Settings icon (SVG) */}
              <span aria-hidden="true">
                <svg width="20" height="20" fill="none" viewBox="0 0 24 24"><circle cx="12" cy="12" r="3" stroke="#222" strokeWidth="2"/><path stroke="#222" strokeWidth="2" d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06A1.65 1.65 0 0 0 15 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 8.6 15a1.65 1.65 0 0 0-1.82-.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.6a1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 15 8.6c.26.17.56.26.86.26s.6-.09.86-.26a1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 15z"/></svg>
              </span>
              Settings
            </Link>
          </nav>
        </aside>
        {/* Main Content */}
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}